import Link from "next/link";

const steps = [
  ["1. Открой Sources", "Нажми «Надёжный пресет»: приложение включит отдельные адаптеры HH, Getmatch, LinkedIn guest, Remote OK, Remotive, Arbeitnow и We Work Remotely. Запросы уже собраны из активного профиля."],
  ["2. Адаптер или Parser", "Адаптер знает конкретный JSON API, RSS или guest feed площадки. Parser нужен только для разовой или неизвестной публичной ссылки. Для закрытой страницы используй Capture или вставь полный текст."],
  ["3. Проверь язык", "В профиле укажи рабочие языки и strict/flexible policy. В strict несовместимый рабочий язык получает hard stop и не засоряет Inbox."],
  ["4. Подключи ключи при необходимости", "Settings → API-ключи источников. Значения шифруются локально, секреты не возвращаются в браузер и не попадают в backup JSON."],
  ["5. Работай через Offer Sprint", "Открой подходящую вакансию. Базовый пакет появится сразу: он строится локальными правилами и не тратит токены. Если нужен глубоко персональный вариант, нажми «Сгенерировать с AI»."],
  ["6. Письмо только после Approve", "В карточке вакансии проверь публичный email, тему и текст, приложи PDF/DOCX резюме и поставь подтверждающую галочку. Без SMTP, файла и явного Approve & Send письмо не уйдёт."],
];

export default function HelpPage() {
  return <div className="space-y-5"><div><h1 className="text-2xl font-black md:text-3xl">Как пользоваться JOB RADAR</h1><p className="mt-1 text-[var(--muted)]">Короткая инструкция без технических терминов.</p></div><section className="panel p-5 md:p-7"><div className="space-y-5">{steps.map(([title, body]) => <div key={title} className="border-b pb-5 last:border-0 last:pb-0"><h2 className="font-black">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">{body}</p></div>)}</div></section><section className="panel p-5 md:p-7"><h2 className="font-black">Как работает AI</h2><div className="mt-3 max-w-3xl space-y-2 text-sm leading-6 text-[var(--muted)]"><p>AI полностью опционален. Добавь свой OpenAI API key в <Link href="/settings" className="font-semibold text-blue-600 hover:underline">Settings</Link>, затем нажми кнопку внутри конкретной вакансии. До клика никакого запроса к модели и расходов нет.</p><p>Сервер отправляет модели только данные активного профиля и выбранной вакансии, просит вернуть стратегию, письмо, follow-up и подготовку к интервью. Ключ остаётся на сервере. Результат нужно проверить: AI не имеет права придумывать опыт и достижения, но финальное решение всегда за тобой.</p></div></section><section className="panel p-5 md:p-7"><h2 className="font-black">Если что-то не работает</h2><ul className="mt-3 max-w-3xl space-y-2 text-sm leading-6 text-[var(--muted)]"><li>• `unavailable` — ссылка действительно недоступна; вакансия архивируется.</li><li>• `unknown` — источник временно ограничил запрос; это не означает, что вакансия плохая.</li><li>• Parser просит URL или текст — вставь ссылку именно на вакансию либо её описание, а не пустой запрос.</li><li>• Parser просит Capture — страница закрыта логином, CAPTCHA или не содержит структурированных данных.</li><li>• Источник показывает SETUP — добавь ключ в <Link href="/settings" className="font-semibold text-blue-600 hover:underline">Settings</Link> или используй Parser.</li></ul></section><div className="flex flex-wrap gap-3"><Link href="/sources/hh" className="rounded-md bg-[var(--accent)] px-4 py-2 text-sm font-bold text-white">Перейти к Sources</Link><Link href="/settings" className="rounded-md border px-4 py-2 text-sm font-bold">Настроить ключи</Link></div></div>;
}
